### ISSUE TITLE
Plot Key by name

### ISSUE THREAD

**Issue by jcc10** [brandon3055/Town-Builder#2]
Could we get a way of setting plot keys by a name so we can just sell one type of key and it will work on any house set to that key name?

This would allow for several levels of houses but all sold with the same key.

**Comment by brandon3055** [comment]
I think what your asking for is already possible. As of the latest version you are able to link one key to as many builder blocks as you like. That key can then be copied and used and used on all of the linked builder blocks.

**Comment by jcc10** [comment]
No, I am talking about setting a string for a key set, you set the string
in the block(s) then match the key to the block, backwards compatibility
would be the blocks key-string being the x,y,z of the block.

**Comment by brandon3055** [comment]
Ok so you mean you set a string in the block and you set a string in the key. Then if block string = key string then key activates block?

**Comment by jcc10** [comment]
Yes, which allows adding of new blocks without having to get more keys.

Also if I guess right, you're using a array of array's(xyz cords) to look
for the block, this would be faster if you have more than a few.

BONUS THING: (I'm learning Java so I may try adding this in later) Making a
menu that lists the houses you can buy for the plot based off of lists of
houses. (again not on issue but random idea)

**Comment by brandon3055** [comment]
The way it currently works is when you bind a key to a boulder block a random integer is generated. That int is saved to both the key and the block and is used as a sort of key code. If you right click an unset block with a key that is already set it dose not generate a new number but instead uses the number already saved to the key. So it already works similar to how you are suggesting but it uses an int instead of a string. And you can not choose the int it uses (unless you use an nbt editor) It is theoretically possible to get conflicting key codes but it is a 1 in 2,147,483,647 chance so i am not too worried about it.

On a side note i have been thinking about switching to a currency based system where instead of using keys you give the player ether an item worth so many points or perhaps use a custom player stat as their currency. You could then just set the cost for each house respectively.

**Comment by TimoMeijer** [comment]
Conflicting key codes will get more common the more structures you have, it might be more secure to store a global counter, and whenever you need an id, up the counter by one and use that integer.

**Comment by spannerman79** [comment]
> On a side note i have been thinking about switching to a currency based system

Would it be possible to look into seeing if you can hook/look into seeing if that can be done via the mod [Universal Coins](https://github.com/notabadminer/UniversalCoinsMod)?

People using Cauldron can use the plugin bridge that notabadminer has a bridge that connects the  two into Vault so there is an economy based system there.

I'm just not sure if there is a Vault mod for 1.7.10
